### ISSUE TITLE
User Friendly GUI

### ISSUE THREAD

**Issue by avatar4444** [SIU-CS/team_18-production#1]
As a user, I want to be able to look at a calendar that allows me to see changes to my total amount of money so that I can easily visualize and edit my budget plan over time.

**Acceptance criteria:**

1. User can choose three views: a weekly view, a view of a month, and a view of the year.
2. Depending on the view selected, the user will see different levels of detail for their expenditures/accumulations during that time frame.
3. Tapping on a day provides more detail and opens the option to edit it.

**Estimate: 48 man-hours**

**Comment by elementfrvr** [comment]
Done
