### ISSUE TITLE
Budgeting System

### ISSUE THREAD

**Issue by avatar4444** [SIU-CS/team_18-production#2]
As a user, I want to be able to add and remove losses and gains so that I can keep track of how much money I have saved and spent.

**Acceptance criteria:**
1.	User can add/remove an addition/subtraction to their income. These can be labelled as various preset types, or as a custom type.
2.	Each type of expenditure will have a priority level. Having insufficient funds to pay for a high-priority expense will create a warning. Expenditures with custom labels will also have custom priority levels.
3.	User can input their income which will be applied to their budget.
4.	User can add/remove money from their current funds for unexpected occurrences.

**Estimate:  168 man-hours**

**Comment by elementfrvr** [comment]
Done
