### ISSUE TITLE
Financial Health Algorithm Tweaks 

### ISSUE THREAD

**Issue by avatar4444** [SIU-CS/team_18-production#28]
As a user, I want to have a quick readout of my financial status so that I can tell at a glance if I am in financial trouble.

**Acceptance Criteria:**

1. Financial health shows current financial status (Very Poor, Poor, Fair, Good, Excellent)
2. Amount of money the user currently has is factored into overall financial health status.
3. Status is also based on whether the current balance is enough to pay upcoming expenses depending on their importance.
4. Paychecks coming before the bills are due should also be recognized by the program.

**Comment by elementfrvr** [comment]
Done
