### ISSUE TITLE
Improvements of App Appearance 

### ISSUE THREAD

**Issue by avatar4444** [SIU-CS/team_18-production#29]
As a user, I would like a user-friendly eye-appealing database so that my experience using the app is comfortable and enjoyable.

**Acceptance Criteria:**

1. Alter color scheme to be more appealing, the excessive dark grays are not satisfactory.
2. Either change the buttons for screen switching to look better, or replace them with swiping between screens.
3. Generally reorganize the screens to make them more accessible and easy to read.
4. Rework the layout of Budget Summary to better fit the information provided

Estimate: 24 man-hours

**Comment by elementfrvr** [comment]
@iantodd96 I added another Acceptance criterion

**Comment by iantodd96** [comment]
I've gotten the GUI to a point where I feel comfortable calling it done.
