### ISSUE TITLE
Calendar View 

### ISSUE THREAD

**Issue by avatar4444** [SIU-CS/team_18-production#30]
As a user, I would like a calendar view so that I can see exactly when certain expenditures or gains are coming easily.

**Acceptance Criteria:**

1. Calendar days can be tapped and viewed in more detail.
2. From the calendar, you can add or remove expenditures and income.
3. Calendar days are highlighted in a color if they have a bill/payday.

Estimate: 48 man-hours

**Comment by elementfrvr** [comment]
Cut feature
